/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeWorkArea;

import UserInterface.EnterpriseWorkQueues.ManufacturerWorkQueueJPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import UserInterface.EnterpriseWorkQueues.HealthcareWorkQueueJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author divinity
 */
public class AdministrativeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdministrativeWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem business;
    private UserAccount account;
    public AdministrativeWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        System.out.println("Garima is displaying enterprise type: "+enterprise.getEnterpriseType());
        if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.HealthcareProvider)){
            System.out.println("Healthcare Provider");
            deviceCatalogjButton.setEnabled(false);
        }
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
        System.out.println(enterprise);
        System.out.println(enterprise.getEnterpriseType());
        this.business = business;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        employeeAccessJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        deviceCatalogjButton = new javax.swing.JButton();
        workQueueJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(201, 218, 229));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        employeeAccessJButton.setText("Manage Employee Access");
        employeeAccessJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeAccessJButtonActionPerformed(evt);
            }
        });
        add(employeeAccessJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, -1));

        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, -1));

        deviceCatalogjButton.setText("Manage Device Catalogue");
        deviceCatalogjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceCatalogjButtonActionPerformed(evt);
            }
        });
        add(deviceCatalogjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 200, -1));

        workQueueJButton.setText("Manage Work Queue");
        workQueueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workQueueJButtonActionPerformed(evt);
            }
        });
        add(workQueueJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void employeeAccessJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeAccessJButtonActionPerformed
        // TODO add your handling code here:
        ManageEmployeeAccessJPanel manageEmployeeJPanel = new ManageEmployeeAccessJPanel(userProcessContainer,  enterprise);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_employeeAccessJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageNetworkJPanel=new ManageOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void deviceCatalogjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceCatalogjButtonActionPerformed
        // TODO add your handling code here:
        ManageDeviceJPanel managedevice=new ManageDeviceJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("device",managedevice);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_deviceCatalogjButtonActionPerformed

    private void workQueueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workQueueJButtonActionPerformed
        // TODO add your handling code here:
        if(enterprise.getEnterpriseType().toString().equals("Manufacturer")){
        ManufacturerWorkQueueJPanel managemanufacturerequeue =new ManufacturerWorkQueueJPanel(userProcessContainer, account, enterprise, business);
        userProcessContainer.add("manufacturequeue",managemanufacturerequeue);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        
        else if((enterprise.getEnterpriseType().toString().equals("Healthcare Provider"))){
        HealthcareWorkQueueJPanel managehealthcarequeue =new HealthcareWorkQueueJPanel(userProcessContainer, account, enterprise, business);
        userProcessContainer.add("healthcarequeue",managehealthcarequeue);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        
    }//GEN-LAST:event_workQueueJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deviceCatalogjButton;
    private javax.swing.JButton employeeAccessJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton workQueueJButton;
    // End of variables declaration//GEN-END:variables
}
