/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AuthorizationOrganization;
import Business.Organization.Organization;
import Business.Organization.SalesOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AuthorizationLevelWorkRequest;
import Business.WorkQueue.SalesLevelWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.EnterpriseWorkQueues.OrganisationEmailJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class SalesWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SalesOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private Organization org;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public SalesWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SalesOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        this.business = business;
        System.out.println("My Papa " + enterprise.getName());
        populateRequestTable();

    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        System.out.println("device selected start populate");
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {

            System.out.println("device " + request.getDevice());
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getEnterprise();
            row[2] = request.getStatus();
            row[3] = request.getStatus();
            String result = ((SalesLevelWorkRequest) request).getTestResult();

            row[4] = result == null ? "Waiting" : result;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        sendEmailButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        ForwardReqtoHCP = new javax.swing.JButton();
        OrderDeliverBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 224, 225));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device", "Enterprise", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        requestTestJButton.setText("Initiate New Sale");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        valueLabel.setText("<value>");

        sendEmailButton.setText("Send Email");
        sendEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enterpriseLabel.setText("Enterprise :");

        ForwardReqtoHCP.setText("Forward to HCP");
        ForwardReqtoHCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardReqtoHCPActionPerformed(evt);
            }
        });

        OrderDeliverBtn.setText("Deliver Order");
        OrderDeliverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDeliverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(requestTestJButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ForwardReqtoHCP)
                                    .addGap(18, 18, 18)
                                    .addComponent(sendEmailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(refreshTestJButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(OrderDeliverBtn)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel)
                    .addComponent(enterpriseLabel))
                .addGap(9, 9, 9)
                .addComponent(refreshTestJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestTestJButton)
                    .addComponent(sendEmailButton)
                    .addComponent(ForwardReqtoHCP))
                .addGap(18, 18, 18)
                .addComponent(OrderDeliverBtn)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("approval Jpanel", new DeviceApprovalJPanel(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void sendEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailButtonActionPerformed
        // TODO add your handling code here:
        OrganisationEmailJPanel orgEmailCommunication = new OrganisationEmailJPanel(userProcessContainer, userAccount, enterprise, org);
        userProcessContainer.add("orgEmailCommunication", orgEmailCommunication);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sendEmailButtonActionPerformed

    private void ForwardReqtoHCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardReqtoHCPActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a Request !!");
            return;

        }

        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        if (request.getStatus().equals("From Manufactuer")) {
            JOptionPane.showMessageDialog(null, "fourward req start to auth");
            AuthorizationLevelWorkRequest requestObjForAuthenticator = new AuthorizationLevelWorkRequest();

            requestObjForAuthenticator.setDevice(request.getDevice());
            requestObjForAuthenticator.setEnterprise(request.getEnterprise());
            requestObjForAuthenticator.setSender(userAccount);
            requestObjForAuthenticator.setStatus("To Be Processed");
            requestObjForAuthenticator.setParentId(request.getRequestId());

            business.getAllWorkList().add(requestObjForAuthenticator);
            JOptionPane.showMessageDialog(null, "object created for auth");

            for (Network net : business.getNetworkList()) {
                for (Enterprise enter : net.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enter.getName().equals(request.getEnterprise().getName())) {
                        for (Organization org1 : enter.getOrganizationDirectory().getOrganizationList()) {
                            if (org1 instanceof AuthorizationOrganization) {
                                org1.getWorkQueue().getWorkRequestList().add(requestObjForAuthenticator);
                                request.setStatus("Sent to Healthcare");
                                JOptionPane.showMessageDialog(null, "Request is forward to Healthcare auth dep!");
                            }
                        }

                    }
                }
            }
        }
    }//GEN-LAST:event_ForwardReqtoHCPActionPerformed

    private void OrderDeliverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDeliverBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a Request !!");
            return;
        }

        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        if (request.getStatus().equals("Order Placed")) {

            ChangeStatustoOrderDeliver(request);

        } else {
            JOptionPane.showMessageDialog(null, "You can't place order for this request !");
        }

    }//GEN-LAST:event_OrderDeliverBtnActionPerformed

    public void ChangeStatustoOrderDeliver(WorkRequest req) {
        String reqId = req.getRequestId();
        for (WorkRequest request : business.getAllWorkList()) {
            System.out.println("Request id for device  " + request.getRequestId());
            String P_ID = request.getParentId();
            if (P_ID != null && P_ID.equalsIgnoreCase(reqId)) {
                System.out.println("matching ids : sale " + req.getRequestId() + "auth parent: " + request.getParentId());
                System.out.println("parent found for authorization ");
                System.out.println("authorization before update " + request.getStatus());
                request.setStatus("Order Delivered");
                System.out.println("authorization after update " + request.getStatus());
                System.out.println("sales before update " + req.getStatus());
                req.setStatus(request.getStatus());
                System.out.println("sales after update " + req.getStatus());
                ChangeStatustoOrderDeliverToManu(req);
                break;
            }
        }

    }

    public void ChangeStatustoOrderDeliverToManu(WorkRequest req) {
        String P_reqId = req.getParentId();
        for (WorkRequest request : business.getAllWorkList()) {
            if (request.getRequestId().equals(P_reqId)) {
                request.setStatus(req.getStatus());
                break;
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ForwardReqtoHCP;
    private javax.swing.JButton OrderDeliverBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton sendEmailButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
